version: "3"
services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
    - ./html:/usr/share/nginx/html
    - ./config:/etc/nginx/conf.d
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  v2fly:
    image: v2fly/v2fly-core:v5.2.1
    container_name: v2fly
    network_mode: host
    volumes:
      - ./config:/etc/v2ray
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command: ["run", "-config=/etc/v2ray/config.json"]
